name: Resmi
favicon: null
layout_spectrum: 0.7805617093108594
typography_spectrum: 0.09178755595348775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3431139192543924
  lightness: 0.6587454967666417
  saturation: 0.20020601665601134
  rhythmicContrast: 0.3526205543894321
purpose: []
